name: country_calling_code_picker
description: Flexible Country picker for getting Country code and Calling code.
version: 2.0.1
homepage: https://github.com/dev-naiksan/country-calling-code-picker.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sim_country_code: ^0.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - flags/
    - raw/
